CREATE TABLE ITMT 
   (	ID INT, 
	ID_ANTERIOR INT, 
	IMAGEN VARCHAR(4000), 
	FLAG_MODO INT, 
	ORDEN INT, 
	VISIBLE INT, 
	LINK_A_SECCION INT, 
	LINK_EXTERNO VARCHAR(4000), 
	FLAG_EMERGENTE INT, 
	ANCHO INT, 
	ALTO INT, 
	URL_TEXTO VARCHAR(4000), 
	FLAG_INDICE INT, 
	FLAG_RESIZABLE VARCHAR(4000), 
	PRIMERO VARCHAR(4000), 
	FLAG_PORTADA INT DEFAULT 0
   );

CREATE TABLE ITMT_I 
   (	ID INT, 
	ID_IDIOMA INT, 
	TITULO VARCHAR(4000), 
	ENTRADILLA VARCHAR(4000), 
	ALTIMAGEN VARCHAR(4000), 
	ENTRADILLA_LISTA_DESCARGA VARCHAR(4000)
   );

CREATE TABLE BLOQUETEXTO 
   (	ID INT, 
	ID_ITMT INT, 
	IMAGEN VARCHAR(4000), 
	URL VARCHAR(4000), 
	TITULO_VISIBLE VARCHAR(4000), 
	PLANTILLA VARCHAR(4000), 
	ORDEN INT, 
	ANCHO INT, 
	ALTO INT, 
	FLAG_RESIZABLE VARCHAR(1000), 
	FLAG_EMERGENTE VARCHAR(1000)
   );

CREATE TABLE BLOQUETEXTO_I 
   (	ID INT, 
	ID_IDIOMA INT, 
	TITULO VARCHAR(4000), 
	TEXTO VARCHAR(4000), 
	ALTIMAGEN VARCHAR(4000)
   );